# Generated by Django 6.0.3 on 2026-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=255)),
                ('hospital', models.CharField(default='HAMS Hospital', max_length=255)),
                ('address', models.CharField(default='Dhumbarahi, Kathmandu', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('fees', models.IntegerField(default=1000)),
                ('years_experience', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
